name: Pipeline

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up project files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Snyk client
      run: wget https://github.com/snyk/snyk/releases/download/v1.530.0/snyk-linux; chmod +x ./snyk-linux; mv ./snyk-linux ./snyk

    - name: Set up compile and build
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile and Build (Gradle)
      run: ./build.sh
      
    - name: Code Analysis (Sonar)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./codeAnalysis.sh

    - name: Libraries Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./librariesAnalysis.sh

    - name: Packaging (Docker images)
      run: ./package.sh

    - name: Package Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
      run: ./packageAnalysis.sh

    - name: Publishing (Github Packages)
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh