name: Pipeline

on:
  push:
    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant permissions
      run: chmod +x gradlew; chmod +x *.sh

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./build.sh

    - name: Packaging
      run: ./package.sh

    - name: Publishing
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh

    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: apply -f pod.yaml