name: Pipeline

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up project files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Snyk client
      run: wget https://github.com/snyk/snyk/releases/download/v1.530.0/snyk-linux; mv ./snyk-linux ./snyk; chmod +x ./snyk;

    - name: Set up Kubernetes client
      run: curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"; mv kubectl.sha256 kubectl; chmod +x kubectl;

    - name: Set up compile and build
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile and Build (Gradle)
      run: ./build.sh
      
    - name: Code Analysis (Sonar)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./codeAnalysis.sh

    - name: Libraries Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./librariesAnalysis.sh

    - name: Packaging (Docker images)
      run: ./package.sh

    - name: Package Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
      run: ./packageAnalysis.sh

    - name: Publishing (Github Packages)
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh

    - name: Deploy (Kubernetes)
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      run: ./deploy.sh