name: Pipeline

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up project files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up pipeline permissions
      run: chmod +x gradlew; chmod +x *.sh

    - name: Set up Snyk client
      run: wget https://github.com/snyk/snyk/releases/download/v1.530.0/snyk-linux; chmod +x ./snyk-linux

    - name: Set up compile and build
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile and Build (Gradle)
      run: ./gradlew clean build
      
    - name: Code Analysis (Sonar)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonarqube

    - name: Libraries Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./snyk-linux monitor

    - name: Packaging (Docker image)
      env:
        CONTRAST_CONFIG_DATA: ${{ secrets.CONTRAST_CONFIG_DATA }}
      run: ./package.sh

    - name: Package Analysis (Snyk)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: ./snyk-linux container test fvilarinho/demo:latest

    - name: Publishing (Github Packages)
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      run: ./publish.sh

    - name: Clear cluster
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: delete pods --all

    - name: Deploy in cluster
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: apply -f pod.yaml
